#paths:
repo_path: Rocket_RL/
#data
data_file_path: data/rocket_data.csv #most of the data
result_path: results/
#both of the below are in the results folder
pickle_path: pickles/
data_result_path: data/figures/
labels_path: video_labels/
ray_results_path: ray_results/RocketRL/

#model
#both of the below are in the results folder
pickle_path: pickles/
model_result_path: model/figures/

#Model variables

# Regression variables: 
reg_model: lasso #either linreg or lasso. LASSO CV for L1 regularization
# Alpha (regularization strength) of LASSO regression
lasso_eps: 0.0001
lasso_nalpha: 40
lasso_iter: 500000
cv: 5

# Min and max degree of polynomials features to consider
degree_min: 3
degree_max: 3
# Test/train split
test_set_fraction: .2

# RL Variables:

# Environment variables: 
# The MSE threshold to determine whether the agent has reached the goal 
# for each of the 3 inputs
MSE_thresh1: 0.01
MSE_thresh2: 0.01
MSE_thresh3: 0.01

# Reward upon reaching the goal
reward: 10000

# Scaling variable for the MSE:
MSE_scale: 1000 #multiply the MSE by this to get negative reward

# Action range: can go up or down this amount
action_range: 0.2

# Noise is really an add-on to the regression model: it adds some random noise to
# the deterministic regression output to more closely mimic the simulation space
# Remember that the range of any variable is 0 - 1
noise: 0

# This removes the top & bottom fraction of the input space.
# The range is 0-1
minmaxbuffer: 0

# Experiment variables:
  #Stopping conditions:
time_total_s: 600000
timesteps_total: 100000000
episode_reward_mean: 10000

checkpoint-freq: 1

num_workers: 3 # 1 fewer than available CPU!


# PPO agent variables:
gamma: 0.995 # Discount factor of the MDP
horizon: 2000 # Number of steps after which the rollout gets cut
num_sgd_iter: 30 #Number of stochastic gradient descent iterations in each outer loop
sgd_stepsize: 0.00005
timesteps_per_batch: 4000
min_steps_per_task: 200



# Rendering settings that may need to be tweaked per model:
buff_axis: 0.2 #buffer for top & bottom of screen 
scalestep: 100 #number steps

#plot variables:
#video:

ftype: .png
labels:
  - G1F
  - G1T
  - G2F
  - G2T
  - O1
  - O2
  - O3

#3d data plot columns:
xvar: 1
yvar: 2
zvar: 0



fs: 14 #fontsize for x & y labels

#Data variables


#data management variables: 

#variables to change the scale for:
change_scale:
  - I_CH4_g/s
  - I_O2_g/s

#naming
in_var:
  - I_CH4_g/s
  - I_CH4_t
  - I_O2_g/s
  - I_O2_t

out_var:
  - O_CH4_flow_uniformity
  - O_CH4_mol_frac
  - O_t

#corresponding names, for figure labeling: 
in_var_name:
  - CH4 flow rate, g/s
  - CH4 temp (K)
  - O2 flow rate, g/s
  - O2 temp (K)'

out_var_name:
  - CH4 flow uniformity
  - CH4 mol frac
  - output temp (K)