#paths:
data_file_path: data/rocket_data.csv #most of the data
result_path: results/
pickle_path: pickles/
fig_path: data/figures/

#regression variables: 
# Alpha (regularization strength) of LASSO regression
lasso_eps: 0.0001
lasso_nalpha: 40
lasso_iter: 500000
# Min and max degree of polynomials features to consider
degree_min: 4
degree_max: 4
cv: 5
# Test/train split
test_set_fraction: .1



#data management variables: 

#variables to change the scale for:
change_scale:
  - I_CH4_g/s
  - I_O2_g/s

#naming
in_var:
  - I_CH4_g/s
  - I_CH4_t
  - I_O2_g/s
  - I_O2_t

out_var:
  - O_CH4_flow_uniformity
  - O_CH4_mol_frac
  - O_t

#corresponding names, for figure labeling: 
in_var_name:
  - CH4 flow rate, g/s
  - CH4 temp (K)
  - O2 flow rate, g/s
  - O2 temp (K)'

out_var_name:
  - CH4 flow uniformity
  - CH4 mol frac
  - output temp (K)


#TO DO: move this to relevant func when done
#data

#Observations that are the basis of plotted variables:
#O2 flow rate is highly predictive of CH4 flow uniformity & CH4 mol frac
#O2 temp is highly predictive of output temp
#CH4 flow rate is slightly predictive of CH4 mol frac
#O2 temp is slightly predictive of CH4 flow uniformity

#Plot the specific variables based on the above observations:
xs:
  - I_O2_t
  - I_O2_g/s
  - I_O2_g/s
  - I_CH4_g/s
  - I_O2_t

ys:
  - O_t
  - O_CH4_flow_uniformity
  - O_CH4_mol_frac
  - O_CH4_mol_frac
  - O_CH4_flow_uniformity

#corresponding name
x_names:
  - O2 temp (K)
  - O2 flow rate, g/s
  - O2 flow rate, g/s
  - CH4 flow rate, g/s
  - O2 temp (K)

y_names:
  - output temp (K)
  - CH4 flow uniformity
  - CH4 mol frac
  - CH4 mol frac
  - CH4 flow uniformity
