#paths:
result_path: results/
pickle_path: pickles/
fig_path: model/figures/

#Nina variables:
training: True #toggle this to train or deploy model
testing: 1 #1 is 50* change; 2 is random; 3 is max to min 

#RL model variables:

gamma: 0.618
n_exp: 20 # number of experiments to run 


 
max_steps: 5000  #terminate an episode past this #
#plotting variables:

#plot variables:

fs: 14 #fontsize for x & y labels

#TO DO: move this to relevant func. when done
#RL plots:
colors:
  Total Reward: k
  Reward: b
  episodes: g
  Input Temp1: m
  Input Temp2: r
  Output Temp: k
  Num steps: k
  Action: g 
  Target: y 

